services:

  # Python application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app

      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}

    expose:
      - "8000"

    volumes:
      # Python: read/write
      - ./images:/app/images
      - ./logs:/app/logs

    networks:
      - app-network


  # NGINX
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx

    ports:
      - "8080:80"

    volumes:
      - ./images:/app/images:ro
      - ./logs:/logs

    depends_on:
      - app

    networks:
      - app-network


  # Internal Docker network
networks:
  app-network:
    driver: bridge