BEGIN;

-- =========================================
-- 1. TABLE
-- =========================================

CREATE TABLE IF NOT EXISTS public.images (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename      TEXT NOT NULL,
    original_name TEXT NOT NULL,
    size          BIGINT NOT NULL CHECK (size >= 0),
    upload_time   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    file_type     TEXT NOT NULL
);


-- =========================================
-- 2. INDEX
-- =========================================

CREATE INDEX IF NOT EXISTS idx_images_upload_time_id
    ON public.images (upload_time DESC, id DESC);


-- =========================================
-- 3. CREATE IMAGE
-- =========================================

CREATE OR REPLACE FUNCTION public.create_image(
    p_filename      TEXT,
    p_original_name TEXT,
    p_size          BIGINT,
    p_file_type     TEXT
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $function$
DECLARE
    v_id BIGINT;
BEGIN
    IF p_filename IS NULL OR btrim(p_filename) = '' THEN
        RAISE EXCEPTION 'filename must not be empty'
            USING ERRCODE = '22023';
    END IF;

    IF p_original_name IS NULL OR btrim(p_original_name) = '' THEN
        RAISE EXCEPTION 'original_name must not be empty'
            USING ERRCODE = '22023';
    END IF;

    IF p_size IS NULL OR p_size < 0 THEN
        RAISE EXCEPTION 'size must be non-negative'
            USING ERRCODE = '22023';
    END IF;

    IF p_file_type IS NULL OR btrim(p_file_type) = '' THEN
        RAISE EXCEPTION 'file_type must not be empty'
            USING ERRCODE = '22023';
    END IF;

    INSERT INTO public.images (
        filename,
        original_name,
        size,
        file_type
    )
    VALUES (
        p_filename,
        p_original_name,
        p_size,
        p_file_type
    )
    RETURNING id INTO v_id;

    RETURN v_id;
END;
$function$;


-- =========================================
-- 4. GET IMAGES WITH PAGINATION
-- =========================================

CREATE OR REPLACE FUNCTION public.get_images(
    p_page      INTEGER DEFAULT 1,
    p_page_size INTEGER DEFAULT 20
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
AS $function$
DECLARE
    v_page      INTEGER;
    v_page_size INTEGER;
    v_offset    BIGINT;
    v_result    JSONB;
BEGIN
    v_page := GREATEST(COALESCE(p_page, 1), 1);

    v_page_size := LEAST(
        GREATEST(COALESCE(p_page_size, 20), 1),
        100
    );

    v_offset := (v_page::BIGINT - 1) * v_page_size;

    SELECT COALESCE(
        jsonb_agg(
            to_jsonb(page_rows)
            ORDER BY page_rows.upload_time DESC, page_rows.id DESC
        ),
        '[]'::JSONB
    )
    INTO v_result
    FROM (
        SELECT
            id,
            filename,
            original_name,
            size,
            file_type,
            upload_time
        FROM public.images
        ORDER BY upload_time DESC, id DESC
        LIMIT v_page_size
        OFFSET v_offset
    ) AS page_rows;

    RETURN v_result;
END;
$function$;


-- =========================================
-- 5. GET PAGINATION METADATA
-- =========================================

CREATE OR REPLACE FUNCTION public.get_pagination(
    p_page      INTEGER DEFAULT 1,
    p_page_size INTEGER DEFAULT 20
)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
AS $function$
DECLARE
    v_page        INTEGER;
    v_page_size   INTEGER;
    v_total_items BIGINT;
    v_total_pages BIGINT;
BEGIN
    v_page := GREATEST(COALESCE(p_page, 1), 1);

    v_page_size := LEAST(
        GREATEST(COALESCE(p_page_size, 20), 1),
        100
    );

    SELECT COUNT(*)
    INTO v_total_items
    FROM public.images;

    v_total_pages :=
        CEIL(v_total_items::NUMERIC / v_page_size)::BIGINT;

    RETURN jsonb_build_object(
        'total_items', v_total_items,
        'page', v_page,
        'page_size', v_page_size,
        'total_pages', v_total_pages,
        'has_previous', v_page > 1,
        'has_next', v_page < v_total_pages
    );
END;
$function$;


-- =========================================
-- 6. GET IMAGE FILENAME
-- =========================================

CREATE OR REPLACE FUNCTION public.get_image_filename(
    p_image_id BIGINT
)
RETURNS TEXT
LANGUAGE SQL
STABLE
AS $function$
    SELECT filename
    FROM public.images
    WHERE id = p_image_id
      AND p_image_id > 0;
$function$;


-- =========================================
-- 7. UPDATE IMAGE METADATA
-- =========================================

CREATE OR REPLACE FUNCTION public.update_image(
    p_image_id      BIGINT,
    p_original_name TEXT,
    p_size          BIGINT,
    p_file_type     TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $function$
DECLARE
    v_updated INTEGER;
BEGIN
    IF p_image_id IS NULL OR p_image_id <= 0 THEN
        RAISE EXCEPTION 'image_id must be positive'
            USING ERRCODE = '22023';
    END IF;

    IF p_original_name IS NULL OR btrim(p_original_name) = '' THEN
        RAISE EXCEPTION 'original_name must not be empty'
            USING ERRCODE = '22023';
    END IF;

    IF p_size IS NULL OR p_size < 0 THEN
        RAISE EXCEPTION 'size must be non-negative'
            USING ERRCODE = '22023';
    END IF;

    IF p_file_type IS NULL OR btrim(p_file_type) = '' THEN
        RAISE EXCEPTION 'file_type must not be empty'
            USING ERRCODE = '22023';
    END IF;

    UPDATE public.images
    SET
        original_name = p_original_name,
        size = p_size,
        file_type = p_file_type
    WHERE id = p_image_id;

    GET DIAGNOSTICS v_updated = ROW_COUNT;

    RETURN v_updated > 0;
END;
$function$;


-- =========================================
-- 8. DELETE IMAGE
-- =========================================

CREATE OR REPLACE FUNCTION public.delete_image(
    p_image_id BIGINT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $function$
DECLARE
    v_deleted INTEGER;
BEGIN
    IF p_image_id IS NULL OR p_image_id <= 0 THEN
        RAISE EXCEPTION 'image_id must be positive'
            USING ERRCODE = '22023';
    END IF;

    DELETE FROM public.images
    WHERE id = p_image_id;

    GET DIAGNOSTICS v_deleted = ROW_COUNT;

    RETURN v_deleted > 0;
END;
$function$;


-- =========================================
-- 9. ACCESS PRIVILEGES
-- =========================================

-- Разрешаем пользователям подключаться к схеме public.
GRANT USAGE ON SCHEMA public TO PUBLIC;

-- Разрешаем чтение и изменение таблицы.
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE public.images
TO PUBLIC;

-- Разрешаем использовать последовательность IDENTITY.
GRANT USAGE, SELECT
ON SEQUENCE public.images_id_seq
TO PUBLIC;

-- Разрешаем вызывать функции.
GRANT EXECUTE ON FUNCTION
    public.create_image(TEXT, TEXT, BIGINT, TEXT)
TO PUBLIC;

GRANT EXECUTE ON FUNCTION
    public.get_images(INTEGER, INTEGER)
TO PUBLIC;

GRANT EXECUTE ON FUNCTION
    public.get_pagination(INTEGER, INTEGER)
TO PUBLIC;

GRANT EXECUTE ON FUNCTION
    public.get_image_filename(BIGINT)
TO PUBLIC;

GRANT EXECUTE ON FUNCTION
    public.update_image(BIGINT, TEXT, BIGINT, TEXT)
TO PUBLIC;

GRANT EXECUTE ON FUNCTION
    public.delete_image(BIGINT)
TO PUBLIC;


COMMIT;